import{S as q,a as M,i as c}from"./assets/vendor-BnfEfRBi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:a,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a href="${i}">
        <img src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p>Likes <br> ${r}</p>
        <p>Views <br> ${a}</p>
        <p>Comments <br> ${w}</p>
        <p>Downloads <br> ${S}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function R(){f.innerHTML=""}function h(){p.classList.remove("hidden")}function g(){p.classList.add("hidden")}function b(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}const O="https://pixabay.com/api/",T="54780926-f74047f8bb106b77773b760bb";async function L(o,t=1){return(await M.get(O,{params:{key:T,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const v=document.querySelector(".form"),d=v.querySelector("input"),B=document.querySelector(".load-more");let s=1,u="";v.addEventListener("submit",x);B.addEventListener("click",C);function P(){setTimeout(()=>{const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}},100)}async function x(o){o.preventDefault();const t=d.value.trim();if(!t){c.warning({message:"This field cannot be empty",position:"topRight"});return}u=t,s=1,R(),l(),h();try{const n=await L(u,s),i=n.hits;if(i.length===0){c.warning({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}y(i),n.totalHits>15&&b()}catch{c.error({message:"Сталася помилка при завантаженні зображень.",position:"topRight"})}finally{g(),d.value=""}}async function C(){s+=1,l(),h();try{const o=await L(u,s),t=o.hits;if(t.length===0||s*15>=o.totalHits){c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l(),s-=1;return}y(t),P(),b()}catch{c.error({message:"Помилка завантаження. Спробуйте пізніше.",position:"topRight"}),s-=1}finally{g()}}
//# sourceMappingURL=index.js.map
