import{S as w,a as S,i as c}from"./assets/vendor-BnfEfRBi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function m(r){const t=r.map(({webformatURL:n,largeImageURL:i,tags:e,likes:o,views:a,comments:L,downloads:v})=>`
    <li class="gallery-item">
      <a href="${i}">
        <img src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p>Likes <br> ${o}</p>
        <p>Views <br> ${a}</p>
        <p>Comments <br> ${L}</p>
        <p>Downloads <br> ${v}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function $(){f.innerHTML=""}function y(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}const O="https://pixabay.com/api/",R="54780926-f74047f8bb106b77773b760bb";async function g(r,t=1){return(await S.get(O,{params:{key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const b=document.querySelector(".form"),u=b.querySelector("input"),l=document.querySelector(".load-more");let s=1,d="";b.addEventListener("submit",M);l.addEventListener("click",P);function T(){setTimeout(()=>{const r=document.querySelector(".gallery-item");if(r){const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}},100)}async function M(r){r.preventDefault();const t=u.value.trim();if(!t){c.warning({message:"This field cannot be empty",position:"topRight"});return}d=t,s=1,$(),l.classList.add("hidden"),y();try{const i=(await g(d,s)).hits;if(i.length===0){c.warning({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}m(i),s+=1,l.classList.remove("hidden")}catch{c.error({message:"Сталася помилка при завантаженні зображень.",position:"topRight"})}finally{h(),u.value=""}}async function P(){y();try{const r=await g(d,s),t=r.hits;(t.length===0||s*15>=r.totalHits)&&l.classList.add("hidden"),m(t),s+=1,T()}catch{c.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}finally{h()}}
//# sourceMappingURL=index.js.map
