import{S as R,a as M,i as s}from"./assets/vendor-BnfEfRBi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),$=new R(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:i,largeImageURL:n,tags:e,likes:r,views:c,comments:S,downloads:q})=>`
    <li class="gallery-item">
      <a href="${n}">
        <img src="${i}" alt="${e}" />
      </a>
      <div class="info">
        <p>Likes <br> ${r}</p>
        <p>Views <br> ${c}</p>
        <p>Comments <br> ${S}</p>
        <p>Downloads <br> ${q}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function P(){f.innerHTML=""}function h(){p.classList.remove("hidden")}function g(){p.classList.add("hidden")}function b(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}const O="https://pixabay.com/api/",T="54780926-f74047f8bb106b77773b760bb";async function L(o,t=1){return(await M.get(O,{params:{key:T,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const v=document.querySelector(".form"),d=v.querySelector("input"),B=document.querySelector(".load-more"),w=15;let a=1,u="";v.addEventListener("submit",x);B.addEventListener("click",C);function E(){setTimeout(()=>{const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}},100)}async function x(o){o.preventDefault();const t=d.value.trim();if(!t){s.warning({message:"This field cannot be empty",position:"topRight"});return}u=t,a=1,P(),l(),h();try{const i=await L(u,a),n=i.hits;if(n.length===0){s.warning({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}y(n),i.totalHits<=w?(s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):b()}catch{s.error({message:"Сталася помилка при завантаженні зображень.",position:"topRight"})}finally{g(),d.value=""}}async function C(){a+=1,l(),h();try{const o=await L(u,a),t=o.hits;y(t),E(),a*w>=o.totalHits?(s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):b()}catch{s.error({message:"Помилка завантаження. Спробуйте пізніше.",position:"topRight"}),a-=1}finally{g()}}
//# sourceMappingURL=index.js.map
